# Generated by Django 4.2.1 on 2023-08-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.PositiveIntegerField(blank=True, null=True, verbose_name='current')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='size')),
                ('color', models.CharField(blank=True, max_length=150, null=True, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='name')),
                ('surname', models.CharField(max_length=500, verbose_name='surname')),
                ('clothing_size', models.CharField(blank=True, max_length=10, null=True, verbose_name='clothing_size')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='gender')),
            ],
        ),
    ]
