# Generated by Django 4.2.4 on 2023-09-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.PositiveIntegerField(blank=True, null=True, verbose_name='current')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='size')),
                ('color', models.CharField(blank=True, max_length=150, null=True, verbose_name='color')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('clothing_size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер одежды')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='Пол')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Населённый пункт')),
                ('street', models.CharField(blank=True, max_length=255, null=True, verbose_name='Улица')),
                ('house', models.CharField(blank=True, max_length=10, null=True, verbose_name='Дом')),
                ('apartment_office', models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира/офис')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Индекс')),
            ],
        ),
    ]
