# Generated by Django 4.2.1 on 2023-08-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
        migrations.AddField(
            model_name='profile',
            name='apartment_office',
            field=models.CharField(max_length=10, null=True, verbose_name='Квартира/офис'),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='Населённый пункт'),
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='profile',
            name='house',
            field=models.CharField(max_length=10, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(max_length=10, null=True, verbose_name='Индекс'),
        ),
        migrations.AddField(
            model_name='profile',
            name='street',
            field=models.CharField(max_length=255, null=True, verbose_name='Улица'),
        ),
    ]
